name: Gradle Package

on:
  workflow_dispatch: # 允许手动触发
  release:
    types: [created]
  push:
    branches:
      - main
      - master
      - develop
      - 'feature/**' # 可以根据需要添加更多的分支

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Grant execute permission to gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: artifact
        path: build/libs/
        if-no-files-found: error
        retention-days: 90
        compression-level: 6
        overwrite: true
        include-hidden-files: false

    - name: Publish to GitHub Packages
      run: ./gradlew publish
